### ISSUE TITLE
File Connector/Persistence

### ISSUE THREAD

**Issue by Xia0ben** [occiware/MartServer#43]
Context:
For the LinkedData demo, we need a way to access some of the OCCI configuration elements to know how to deploy the different components. For example, when the ozenergy app tells Spark to start an aggregation job, we would need to inspect the OCCI configuration in order to get the proper parameters to give to spark: which host is the master, which host is the replica dedicated to analytics, ...
Another example would be the LinkedData QoS : we would need a way to introspect the OCCI conf to fill in the values of Roboconf-specific (bash scripts (deploy/start.sh)) configuration templates (using sed, OR add a template renderer with mixin-based conf to the connector).

Current workaround:
Get the OCCI conf using a simple wget to the MartServer. Limitation : said OCCI conf is not persisted, like a true OCCI(ware) backend would do.

Possible solution (from worst to best):
- Continue using wget to the MartServer to get all the config and parse it in the project to extract the needed information, BUT OCCI configuration needs to be persisted, otherwise, we would have to rewrite the conf at every MartServer startup.
- Write a File Connector to get files templates automatically filled with OCCI parameters from MartServer : we would give the templates once (so they need to be persisted somewhere) with a call to the connector API (actually, we may need all CRUD operation, since the template might need to be changed once in a while), and an API call would allow us to call for the final conf file made from the template and its OCCI parameters.

**Comment by cgourdin** [comment]
linked with #8

**Comment by cgourdin** [comment]
See documentation in : https://github.com/occiware/MartServer/blob/master/doc/server.md#stop-server

**Comment by cgourdin** [comment]
And here : https://github.com/occiware/MartServer/blob/master/doc/server.md#configuring-the-server

**Comment by Xia0ben** [comment]
Nice, thanks, gonna test this asap for version 1.5 ! :D

**Comment by cgourdin** [comment]
The 1.5 is updated but as in v1, the entity location is not stored on object directly, in consequence, the model has not this information inside. If you want to use this feature, store your entities with /category/uuid ( like /compute/f88486b7-0632-482d-a184-a9195733ddd0 ) to be sure to retrieve it after model reloading. I'm searching a workaround for this issue.

**Comment by Xia0ben** [comment]
So, tried this today : running it locally (mvn clean install -Pwithoccinterface + mvn jetty:run-war) didn't cause any problem, but within a Docker container, I ran into some trouble.

When running in a container, I suppose since it slows down the process (cause it doesn't have access to all of the machine's power), I got a timeout exception on jetty annotations, which was solved by adding the following parameter to the mvn jetty:run-war command in the dockerfile (see https://stackoverflow.com/questions/25229710/jetty-annotation-timeout-reason):
```bash
-Dorg.eclipse.jetty.annotations.maxWait=120
```

I don't know if you'd prefer to mention it in the docs or add it in the pom.xml to be sure no one ever encounters the bug again.

The latest changes also included breaking changes on the configuration file API, which were not mentioned in the documentation, but only in the code of the MartServer.java class:

```java
System.out.println("Minimum config file content: ");
System.out.println("server.port=8080\n" +
    "server.log.directory=/logging/application/logs\n" +
    "server.protocol=http");
```
If the server.protocol=http is not in the file, the application fails without explaining that the config file does not contain the required fields. This problem is addressed in my latest pull requests, by modifying the code and the documentation.

Will come back to you if I stumble upon anything else ;-).

**Comment by Xia0ben** [comment]
So, I tested locally a little bit more: it looks like with the persistence commit, you also included WIP on authentification. It seems that this last point breaks the interaction with the occinterface, be it embedded or separate. If it is embedded, it seems possible to get the data, but the kind selection menu doesn't work anymore.

Any clue of what I could do to repair the link between the two ? ;-)

Thanks !

**Comment by cgourdin** [comment]
There is two thing you must be aware :
 - The default parser is set to text/plain (before application/json) if no header "Content-Type" is set.
 - The authentication is set on basic by default but in v1.5 this is not totally complete (as on 2.0). All validation is true (bouchon). In v1.5, all fixes has not been updated (lack of time last week to do that).
In v2.0 i have added a parameter in configuration file (<b>server.users.mode</b>=none) to cancel authentication and authorization of a user, i must reflect this feature on v1.5 asap. I will do this, this week.

**Comment by cgourdin** [comment]
I've updated Mart server, the default content-type is application/json and server.users.mode=none in default configuration property file.
Please checkout the last version from branch patchv1 and check if all works as expected.

**Comment by Xia0ben** [comment]
Thanks, will check all of that in the beginning of next week ! =)

**Comment by Xia0ben** [comment]
Ok, so now we have both persistence, and a way to easily transform martserver data into config files (https://github.com/occiware/MartBTG): I guess that as soon as I can confirm this is all working properly together, we'll be able to definitively close this issue =).

**Comment by cgourdin** [comment]
Yes, one on server side using configuration model and one with a client side :-)

**Comment by Xia0ben** [comment]
Exactly: MartBTG is meant to be client-side only. Though, what would be best for the long-term would be to have the existing OCCIware generators at runtime, client-side : at least package them, and wrap their existing code with a call to MartServer, the same way it's done in MartBTG (which I heavily documented, it shouldn't be a problem to translate it to Java or any other language).

**Comment by cgourdin** [comment]
Thanks for your contribution, i close this issue.
