### ISSUE TITLE
Better browser support

### ISSUE THREAD

**Issue by Xia0ben** [occiware/MartServer#49]
Hi !

So I started exploring the MartServer API a little bit further, and in order to do so, wanted to use a more appropriate tool than curl to explore the JSON files that were sent back: Firefox.

Firefox, like many other web browsers, comes with pretty good tools for API visualization and exploration, and it is far easier to understand the structure of the response when it is well presented.

Problem is that, with MartServer, when trying to access it simply via typing the address of a resource in a web browser (for example : http://localhost:8081/-/ ), we get an error page: 
![error](https://user-images.githubusercontent.com/10845530/28566599-ee20fcec-712f-11e7-9c42-6bd2035c9c29.png)

The problem seems to be coming from the fact that the default requests in Firefox (and in web browsers in general ?) are sent with the header "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" , instead of the "Accept: application/json" expected by MartServer. It would be very welcome if MartServer would, by default, whatever the header's value, send back the JSON, like the Github API (or any other one) does:

![expected](https://user-images.githubusercontent.com/10845530/28566794-8179a8f4-7130-11e7-8b37-287c65eeb879.png)

It would make dev's life a breeze ;-).

**Comment by cgourdin** [comment]
MartServer is not dedicated to json format output. 
Also if there is an accept header not supported by the server, MartServer will throw away. I could implement playback to json if current header is not supported but it's not a good practice as the client awaits for the accept media format.
If you want to do so, you can implement in MartServer (module org.occiware.mart.servlet --> OCCIServletInputRequest class) a better accept media format management.
I will also wait for your pull request and accept it if it is good and doesn't override text/occi, plain/text and application/json format usage.

**Comment by Xia0ben** [comment]
Thanks for the quick answer =) .

I do believe that as long as no user-friendly answer (that is, not an error) is implemented for any of the formats in the "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,/;q=0.8" header, we would be better off sending the json version, at least for these formats, if not as a general default. However, I agree that doing this is not "strict" behaviour, in fact, it has rather become a de-facto standard as the github example shows.

I'll try to propose an adjustement as soon as I am finished with the current code I'm writing !

**Comment by cgourdin** [comment]
Cool !!! Thanks in advance for your future contribution :-)

**Comment by Xia0ben** [comment]
#51

**Comment by Xia0ben** [comment]
Thanks for merging the pull-request, it should work fine now ;-).
