### ISSUE TITLE
Delete directory lib/

### ISSUE THREAD

**Issue by philippemerle** [occiware/MartServer#5]
Artefacts contained in https://github.com/occiware/MartServer/tree/master/lib must be downloaded from Maven repositories.
1) update pom.xml
2) remove directory lib/

**Comment by cgourdin** [comment]
There is a problem for dependencies org.eclipse.ocl and particularly on org.eclipse.ocl.pivot.
I didn't found any maven repository for org.eclipse.ocl.pivot dependency.
I made an update on pom.xml to manage oss sonatype repo for OCCIware jars.

**Comment by cgourdin** [comment]
See commit db49b54

**Comment by philippemerle** [comment]
Are following jars contained in lib/ required?
* commons-net-3.5.jar
* jcl-over-slf4j-1.7.12.jar
* log4j-1.2.17.jar 
* org.eclipse.emf.common-2.11.0-v20150805-0538.jar
* org.eclipse.emf.ecore-2.11.1-v20150805-0538.jar
* slf4j-api-1.7.19.jar
* slf4j-jdk14-1.5.6.jar
* slf4j-log4j12-1.7.7.jar 
* slf4j-simple-1.7.5.jar

Can they be downloaded from some Maven repositories?

**Comment by cgourdin** [comment]
Sorry, i forgot in my commit to remove them, they have been remove with this fix in commit 798c6b5
